#!/usr/bin/env bash
#
# Uses spaceweather (https://raw.githubusercontent.com/curtis86/spaceweather) data to print current/near-realtime space weather data.
# Author: Curtis Kneisel
# GitHub: https://github.com/curtis86/spaceweather-cli

# Uncomment for debug
#set -x

set -o pipefail

# CONSTANTS
home_d="$( dirname $0 )" ; readonly home_d="$( cd "${home_d}" ; pwd )"
readonly spaceweather_d="/opt/spaceweather"
readonly spaceweather_f="${spaceweather_d}/spaceweather"
readonly libraries_d="${home_d}/libraries"
readonly refresh_rate=10

# SCRIPT FUNCTIONS
abrt() { echo ; echo "$@" 1>&2 ; exit 1 ; }
msg() { echo ; echo "$@" ; }
vmsg() { echo ; [ $verbose ] && echo "$@" >&2 ; }

# INCLUDES
source "${libraries_d}/functions.sh" || abrt "ERROR: unable to load functions file (${libraries_d}/functions.sh). Exiting."
source "${libraries_d}/aurora_strength_indicator.sh" || abrt "ERROR: unable to load ${libraries_d}/aurora_strength_indicator.sh, exiting."

# MAIN
main() {
  # Verify that spaceweather is available
  [ ! -x "${spaceweather_f}" ] && abrt "ERROR: spaceweather not found. Please install first (see: https://github.com/curtis86/spaceweather)"

  # Parse arguments... crudely
  OPTS=$@
  for opt in $@ ; do
    case $opt in
      "--single") single_mode=true ; OPTS=$( echo "$@" | sed "s/${opt}//g" ) ; set -- $OPTS ;;
      "--help") usage && exit ;;
      --*) abrt "ERROR: uknown option: ${opt}. Exiting." ;;
      -*) abrt "ERROR: uknown option: ${opt}. Exiting." ;;
    esac
  done

  if [ ${single_mode} ]; then
    get_measurements
    print_measurements
    exit 0
  else
    clear
    msg "Loading data... "

    while [ true ]; do
      
      get_measurements
      clear_screen
      print_measurements

      next_update=${refresh_rate}
      while [ ${next_update} -ne 0 ] ; do
        echo -ne "Next update in... ${next_update} seconds          \r"
        ((next_update--))
        sleep 1
      done
    done
fi
}

main $@
